python ./main.py \
--subset "cifar100" \
--arch-name "resnet18_modified" \
--factor 1 \
--num-crop 5 \
--mipc 200 \
--ipc 50 \
--stud-name "resnet18_modified" \
--re-epochs 1000 \
--pipeline "particle" \
